const fs = require('fs');
const path = require('path');

const migrationsDir = path.join(__dirname, '..', 'database', 'migrations');
const outDir = path.join(__dirname, '..', 'database', 'seeds');
const outFile = path.join(outDir, 'seed_master.sql');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const files = fs.readdirSync(migrationsDir)
  .filter(f => f.endsWith('.sql'))
  .sort();

let out = [];
out.push('-- Seed master file generated by scripts/generate-seed.js');
out.push('-- Run with: psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB" -f database/seeds/seed_master.sql');
out.push('BEGIN;');

for (const file of files) {
  const p = path.join(migrationsDir, file);
  out.push(`\n-- BEGIN FILE: ${file}`);
  const content = fs.readFileSync(p, 'utf8');
  out.push(content);
  out.push(`-- END FILE: ${file}\n`);
}

out.push('COMMIT;');

fs.writeFileSync(outFile, out.join('\n'));
console.log('Wrote', outFile, 'with', files.length, 'migration files.');
